# Alacritty configuration documentation
# https://alacritty.org/config-alacritty.html

# Theme installation
# https://github.com/catppuccin/alacritty

import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
size = 18.0

[shell]
program = "/opt/homebrew/bin/tmux"
# Attach to 'main' session if one exists, else create a new sessions called 'main'.
# "-D" makes that all other clients connected to the session are detached from the session.
# https://stackoverflow.com/questions/67463932/is-it-possible-to-make-alacritty-starts-with-tmux
args = ["new-session", "-A", "-s", "main", "-D", "-c", "/Users/benjaminlabrecque/apps/home/labrecqb"]

[window]
startup_mode = "Fullscreen"
