#!/bin/bash 

set -e

# Development environment setup

echo "Setting up development environment"

APPS_HOME=$HOME/apps/home/labrecqb

mkdir -p $HOME/.config
mkdir -p $HOME/.config/alacritty

echo "Setting up symlinks"
cd 
ln -sf $APPS_HOME/dotfiles/.zshrc .zshrc
ln -sf $APPS_HOME/dotfiles/.zprofile .zprofile
ln -sf $APPS_HOME/dotfiles/.vimrc .vimrc
ln -sf $APPS_HOME/dotfiles/.gitignore .gitignore
ln -sf $APPS_HOME/dotfiles/.tmux.conf .tmux.conf
ln -sf $APPS_HOME/dotfiles/.gitconfig .gitconfig
ln -sf $APPS_HOME/dotfiles/.alacritty.toml .config/alacritty/alacritty.toml
ln -sf $APPS_HOME/dotfiles/nvim/.config/nvim .config/nvim
echo "Done setting up symlinks"
