#!/bin/bash

mkdir -p ${HOME}/.local/bin

mv ~/.bash_profile ~/.bash_profile.bak
mv ~/.bashrc ~/.bashrc.bak
mv ~/.gitconfig ~/.gitconfig.bak

stow shell-base --target=${HOME}
stow bash --target=${HOME}

stow nvim --target=${HOME}
stow tmux --target=${HOME}
stow git --target=${HOME}
stow clang --target=${HOME}
stow bin --target=${HOME}/.local/bin
