vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.clipboard = "unnamedplus" -- to use system clipboard
vim.opt.tabstop=4 
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab = true
vim.opt.smartindent = false
vim.opt.hidden = false
vim.opt.errorbells = false
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = "~/.vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "80"
vim.opt.termguicolors = true
-- vim.opt.cursorline = true
