vim.opt.nu = true
vim.opt.relativenumber = false
vim.opt.clipboard = "unnamedplus" -- to use system clipboard
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = false
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.colorcolumn = "88"
vim.opt.termguicolors = true
vim.opt.splitright = true
vim.opt.cursorline = true
vim.opt.guicursor = ""
vim.g.slime_target = 'tmux'
